# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#         python -m pytest --ignore=rational/mxnet/tests --ignore=rational/keras/tests/ -k rational/torch/tests/
name: Python package

on:
  push:
    branches: [ ci-cd ]

jobs:
  manylinux:
    name: Tests Cuda 10.1, Python
    runs-on: GPU4
    steps:
    - uses: actions/checkout@v2
    - name: Current dir
      run: pwd
    - run: nvidia-smi
    - name: Install wheels
      run: |
        ls -l
        docker exec rat_manylinux bash < .github/workflows/compile_and_test.sh
        pwd
        ls
