# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#         python -m pytest --ignore=rational/mxnet/tests --ignore=rational/keras/tests/ -k rational/torch/tests/
name: Python package

on:
  push:
    branches: [ ci-cd ]

jobs:
  manylinux:
    name: Tests Cuda 10.1, Python
    runs-on: GPU4
    steps:
    - uses: actions/checkout@v2
    - name: Current dir
      run: |
        pwd
        ls -l
    - run: nvidia-smi
    - name: Install wheels
      run: |
        docker exec rat_manylinux bash -c 'cd rational_activations && ./pypi_build_scripts/make_manylinux.sh && ls wheelhouse'
        docker exec rat_manylinux bash -c 'cd rational_activations && ls wheelhouse'
        docker exec rat_manylinux bash -c 'cd rational_activations && python3.6 -m pip install wheelhouse/cuda10.2/rational_activations-0.1.0-cp38-cp38-manylinux2014_x86_64.whl'
        docker exec rat_manylinux bash -c 'cd rational_activations && python -c "import sys; print('Python version:', sys.version)"'
        docker exec rat_manylinux bash -c 'cd rational_activations && nvcc --version'
        docker exec rat_manylinux bash -c 'cd rational_activations && python -c "import torch; print('CUDA version used by PyTorch:', torch.version.cuda)"'

        ls /
        ls wheelhouse
        cd rational_activations
        ls wheelhouse
        ls dist
