# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#         python -m pytest --ignore=rational/mxnet/tests --ignore=rational/keras/tests/ -k rational/torch/tests/
name: Python package

on:
  push:
    branches: [ ci-cd ]

jobs:
  manylinux_compilation:
    name: Compile all manylinux wheels
    runs-on: GPU4
    steps:
    - uses: actions/checkout@v2
    - name: Current dir
      run: |
        pwd
        ls -l
    - run: nvidia-smi
  test_wheels:
    name: Tests Python, Cuda =
    needs: manylinux_compilation
    runs-on: GPU4
    strategy:
      matrix:
        python-version: ['3.7'] #, '3.7', '3.8']
        cuda-version: ['10.2']
    steps:
    - uses: actions/checkout@v2
    - name: Run GPU tests CUDA=${{ matrix.cuda-version }} & Python${{ matrix.python-version }}
      run: |
        echo Available wheels:
        docker exec rat_manylinux zsh -c "ls rational_activations/wheelhouse/cuda-${{ matrix.cuda-version }}"
        docker exec rat_manylinux zsh -c "python${{ matrix.python-version }} -m pip uninstall -y rational_activations torch mxnet tensorflow mxnet-cu101 mxnet-cu102"
        docker exec rat_manylinux zsh -c "python${{ matrix.python-version }} -m pip install --upgrade pip"
        docker exec rat_manylinux zsh -c "export CUDA_HOME=/usr/local/cuda-${{ matrix.cuda-version }} && export PATH=/usr/local/cuda-${{ matrix.cuda-version }}/bin:$PATH && nvcc -V && python${{ matrix.python-version }} -m pip install mxnet-cu102 torch==1.7.1 tensorflow-gpu"
        docker exec rat_manylinux zsh -c "cd rational_activations && export CUDA_HOME=/usr/local/cuda-${{ matrix.cuda-version }} && export PATH=/usr/local/cuda-${{ matrix.cuda-version }}/bin:$PATH && nvcc -V && python${{ matrix.python-version }} -m pip install wheelhouse/cuda-${{ matrix.cuda-version }}/rational_activations-0.1.0-cp37-cp37m-manylinux2014_x86_64.whl"
        docker exec rat_manylinux zsh -c "cd /usr/local/lib/python${{ matrix.python-version }}/site-packages/ && export CUDA_HOME=/usr/local/cuda-${{ matrix.cuda-version }} && export PATH=/usr/local/cuda-${{ matrix.cuda-version }}/bin:$PATH && python${{ matrix.python-version }} -m pytest rational"

