# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ ci-cd ]
jobs:


  build-and-test-python37:
    name: Tests Python, CUDA  =
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.7']
        cuda-version: ['10.1', '10.2']
    steps:
      - uses: actions/checkout@v2
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v7
        with:
          default: 3.7.6
          command: |
            pip install -U pip  # upgrade pip after installing python
            pip install airspeed flake8 matplotlib pytest scipy
            pip install torch==1.7.1
            # We need to export correct pointers for CUDA_HOME and nvcc that corresond to the correct CUDA version.
            echo "CUDA_HOME=/usr/local/cuda-${{ matrix.cuda-version }}/" >> $GITHUB_ENV
            echo "PATH=/usr/local/cuda-${{ matrix.cuda-version }}/bin:$PATH" >> $GITHUB_ENV
      - name: create environment
        run: pyenv local 3.7.6 && python -mvenv .venv376
      - name: Check Python and CUDA versions
        run: |
          python --version
          python -c "import sys; print('Python version:', sys.version)"
          python -c "import torch; print('Cuda available:', torch.cuda.is_available())"
          python -c "import torch; print('CUDA version used by PyTorch:', torch.version.cuda)"
          nvcc --version
          echo CUDA_HOME: $CUDA_HOME
      - name: Install package
        run: |
          python setup.py develop
      - name: Test
        run: |
          python -m pytest

# - name: Set Python environment variable
#      run: echo "LD_LIBRARY_PATH=/tmp/runner/work/_tool/Python/${{ matrix.python-version }}/x64/lib" >> $GITHUB_ENV